import './globals.css';
import { M_PLUS_2 } from 'next/font/google';
import Provider from './provider';

const mplus2 = M_PLUS_2({
  subsets: ['latin'],
  variable: '--font-mPlus2'
});

export const metadata = {
  title: 'NoNICK',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={`${mplus2.variable} h-full bg-[url(/background3.jpg)] bg-cover bg-fixed font-mplus2 text-black`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}